Repository NOW-SOPT-SOPKATHON-WEB2/WEB2_BE, pull requests merged in 2024-05, with the labels that each got.

#2 [Feat] #1 - 기초 프로젝트 세팅
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sopt/sopkathon/SopkathonApplication.java
  src/main/java/com/sopt/sopkathon/common/GlobalExceptionHandler.java
  src/main/java/com/sopt/sopkathon/common/dto/CommonResponse.java
  src/main/java/com/sopt/sopkathon/common/dto/ErrorMessage.java
  src/main/java/com/sopt/sopkathon/common/dto/SuccessMessage.java
  src/main/java/com/sopt/sopkathon/config/JpaAuditingConfig.java
  src/main/java/com/sopt/sopkathon/config/WebConfig.java
  src/main/java/com/sopt/sopkathon/controller/AnswerController.java
  src/main/java/com/sopt/sopkathon/controller/QuestionController.java
  src/main/java/com/sopt/sopkathon/controller/ResultController.java
  src/main/java/com/sopt/sopkathon/domain/Answer.java
  src/main/java/com/sopt/sopkathon/domain/BaseTimeEntity.java
  src/main/java/com/sopt/sopkathon/domain/Member.java
  src/main/java/com/sopt/sopkathon/domain/Question.java
  src/main/java/com/sopt/sopkathon/domain/Result.java
  src/main/java/com/sopt/sopkathon/domain/Situation.java
  src/main/java/com/sopt/sopkathon/exceptioon/BusinessException.java
  src/main/java/com/sopt/sopkathon/exceptioon/NotFoundException.java
  src/main/java/com/sopt/sopkathon/repository/AnswerRepository.java
  src/main/java/com/sopt/sopkathon/repository/MemberRepository.java
  src/main/java/com/sopt/sopkathon/repository/QuestionRepository.java
  src/main/java/com/sopt/sopkathon/repository/ResultRepository.java
  src/main/java/com/sopt/sopkathon/repository/SituationRepository.java
  src/main/java/com/sopt/sopkathon/service/AnswerService.java
  src/main/java/com/sopt/sopkathon/service/MemberService.java
  src/main/java/com/sopt/sopkathon/service/QuestionService.java
  src/main/java/com/sopt/sopkathon/service/ResultService.java
  src/main/java/com/sopt/sopkathon/service/SituationService.java
  src/main/java/com/sopt/sopkathon/service/dto/request/ExampleRequestDto.java
  src/main/java/com/sopt/sopkathon/service/dto/response/ExampleResponseDto.java
  src/test/java/com/sopt/sopkathon/SopkathonApplicationTests.java
Labels: 🔧 Chore, 🐻‍❄️ 민재

#10 [Feat] #6 - 답변 조회 API 구현
  .gitignore
  build.gradle
  src/main/java/com/sopt/sopkathon/common/dto/SuccessMessage.java
  src/main/java/com/sopt/sopkathon/controller/AnswerController.java
  src/main/java/com/sopt/sopkathon/repository/AnswerRepository.java
  src/main/java/com/sopt/sopkathon/repository/AnswerRepositoryCustom.java
  src/main/java/com/sopt/sopkathon/repository/AnswerRepositoryCustomImpl.java
  src/main/java/com/sopt/sopkathon/repository/QuestionRepository.java
  src/main/java/com/sopt/sopkathon/service/AnswerService.java
  src/main/java/com/sopt/sopkathon/service/AnswerServiceImpl.java
  src/main/java/com/sopt/sopkathon/service/dto/response/AnswerListResponseDto.java
  src/main/java/com/sopt/sopkathon/service/dto/response/AnswerResponseDto.java
Labels: ✨ Feat, 🔧 Chore, 🌞 서진

#11 [Feat] -#7
  src/main/java/com/sopt/sopkathon/common/GlobalExceptionHandler.java
  src/main/java/com/sopt/sopkathon/common/dto/SuccessMessage.java
  src/main/java/com/sopt/sopkathon/controller/AnswerController.java
  src/main/java/com/sopt/sopkathon/repository/AnswerRepositoryCustom.java
  src/main/java/com/sopt/sopkathon/repository/AnswerRepositoryCustomImpl.java
  src/main/java/com/sopt/sopkathon/service/AnswerService.java
  src/main/java/com/sopt/sopkathon/service/AnswerServiceImpl.java
  src/main/java/com/sopt/sopkathon/service/dto/response/AnswerWeightResponseDto.java
Labels: ✨ Feat, 🌞 서진

#14 [Feat] - #7 content 포함
  src/main/java/com/sopt/sopkathon/repository/AnswerRepositoryCustomImpl.java
  src/main/java/com/sopt/sopkathon/service/dto/response/AnswerWeightResponseDto.java
Labels: ✨ Feat, 🌞 서진
